version: "2.2"
services:
  app:
      container_name: app
      restart: always
      build: ./
      ports:           
        - "3005:3005"
  client:
      container_name: client
      restart: always
      build: ./client
      ports:
        - "3000:3000"
      depends_on:
        - app
